version: '3'
services:
  db:
    build:
        context: ./database
        dockerfile: docker/Dockerfile
    restart: 'always'
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - control_plane

volumes:
  database:
  authn:

networks:
  control_plane:
